import { createClient } from '@/lib/supabase/client';

export interface StoneContainer {
  id: string;
  container_code: string;
  stone_type: string;
  cut: string;
  price_per_ct: number;
  current_stock_ct: number;
  current_stock_units: number;
  notes: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface StoneContainerMovement {
  id: string;
  container_id: string;
  movement_type: 'purchase' | 'sale' | 'adjustment' | 'quotation_use' | 'quotation_return';
  quantity_ct: number;
  quantity_units: number;
  unit_cost: number | null;
  total_cost: number | null;
  reference: string | null;
  notes: string | null;
  quotation_id: string | null;
  registered_by: string | null;
  created_at: string;
  registered_by_user?: { id: string; first_name: string; last_name: string } | null;
}

export const STONE_MOVEMENT_LABELS: Record<StoneContainerMovement['movement_type'], string> = {
  purchase: 'Compra',
  sale: 'Venta',
  adjustment: 'Ajuste',
  quotation_use: 'Uso en cotización',
  quotation_return: 'Devolución cotización',
};

function normalizeContainer(raw: any): StoneContainer {
  return {
    ...raw,
    price_per_ct: Number(raw.price_per_ct) || 0,
    current_stock_ct: Number(raw.current_stock_ct) || 0,
    current_stock_units: Number(raw.current_stock_units) || 0,
  };
}

function normalizeMovement(raw: any): StoneContainerMovement {
  return {
    ...raw,
    quantity_ct: Number(raw.quantity_ct) || 0,
    quantity_units: Number(raw.quantity_units) || 0,
    unit_cost: raw.unit_cost != null ? Number(raw.unit_cost) : null,
    total_cost: raw.total_cost != null ? Number(raw.total_cost) : null,
  };
}

// ── Fetch all containers, optionally filter by stone type ──────────────────
export async function fetchStoneContainers(stoneType?: string): Promise<StoneContainer[]> {
  const supabase = createClient();
  let q = supabase
    .from('stone_containers')
    .select('*')
    .order('stone_type')
    .order('container_code');
  if (stoneType) q = q.eq('stone_type', stoneType);
  const { data, error } = await q;
  if (error) throw error;
  return (data || []).map(normalizeContainer);
}

// ── Fetch single container by code (for quotation lookup) ─────────────────
export async function fetchContainerByCode(code: string): Promise<StoneContainer | null> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('stone_containers')
    .select('*')
    .eq('container_code', code.toUpperCase())
    .eq('is_active', true)
    .single();
  if (error && error.code !== 'PGRST116') throw error;
  return data ? normalizeContainer(data) : null;
}

// ── Create a new container (code generated by DB function) ────────────────
export async function createStoneContainer(payload: {
  stone_type: string;
  cut: string;
  price_per_ct: number;
  notes?: string;
  created_by: string;
}): Promise<StoneContainer> {
  const supabase = createClient();

  // Generate code via DB function
  const { data: codeData, error: codeErr } = await supabase
    .rpc('generate_container_code', { p_stone_type: payload.stone_type });
  if (codeErr) throw codeErr;

  const { data, error } = await supabase
    .from('stone_containers')
    .insert({
      container_code: codeData,
      stone_type: payload.stone_type,
      cut: payload.cut,
      price_per_ct: payload.price_per_ct,
      notes: payload.notes ?? null,
      created_by: payload.created_by,
    })
    .select('*')
    .single();
  if (error) throw error;
  return normalizeContainer(data);
}

// ── Update price of an existing container ─────────────────────────────────
export async function updateContainerPrice(id: string, price_per_ct: number): Promise<void> {
  const supabase = createClient();
  const { error } = await supabase
    .from('stone_containers')
    .update({ price_per_ct, updated_at: new Date().toISOString() })
    .eq('id', id);
  if (error) throw error;
}

// ── Register a movement (purchase, sale, etc.) ────────────────────────────
export async function createContainerMovement(payload: {
  container_id: string;
  movement_type: StoneContainerMovement['movement_type'];
  quantity_ct: number;
  quantity_units: number;
  unit_cost?: number | null;
  reference?: string | null;
  notes?: string | null;
  quotation_id?: string | null;
  registered_by: string;
}): Promise<void> {
  const supabase = createClient();
  const total_cost =
    payload.unit_cost != null ? payload.unit_cost * payload.quantity_ct : null;
  const { error } = await supabase.from('stone_container_movements').insert({
    container_id: payload.container_id,
    movement_type: payload.movement_type,
    quantity_ct: payload.quantity_ct,
    quantity_units: payload.quantity_units,
    unit_cost: payload.unit_cost ?? null,
    total_cost,
    reference: payload.reference ?? null,
    notes: payload.notes ?? null,
    quotation_id: payload.quotation_id ?? null,
    registered_by: payload.registered_by,
  });
  if (error) throw error;
}

// ── Fetch movements for a container ───────────────────────────────────────
export async function fetchContainerMovements(container_id: string): Promise<StoneContainerMovement[]> {
  const supabase = createClient();
  const { data, error } = await supabase
    .from('stone_container_movements')
    .select(`
      *,
      registered_by_user:users!registered_by ( id, first_name, last_name )
    `)
    .eq('container_id', container_id)
    .order('created_at', { ascending: false })
    .limit(50);
  if (error) throw error;
  return (data || []).map(normalizeMovement);
}
